name: palestine_weather_forecasting

channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - openpyxl
  - statsmodels
  - jupyter
  - notebook
  - pip

  - pip:
      - tensorflow
      - keras
      - xgboost
